project:
  type: website
  resources:
    - index.pdf

website:
  title: "István Magyary"
  favicon: favicon.ico
  twitter-card: true
  open-graph: true
  google-analytics:
    tracking-id: "G-3BVSFTG6L3"
    anonymize-ip: true
  cookie-consent: 
    palette: dark
  navbar:
    left:
      - href: index.qmd
        text: Home


format:
  html:
    theme: 
      light: quartz
      dark: darkly
    css: styles.css
    toc: true

pdf:
  toc: false
  number-sections: false
  colorlinks: true



