project:
  type: website
  resources:
    - index.pdf

website:
  title: "István Magyary"
  navbar:
    left:
      - href: index.qmd
        text: Home


format:
  html:
    theme: quartz
    css: styles.css
    toc: true

pdf:
  toc: false
  number-sections: false
  colorlinks: true



