project:
  type: website
  resources:
    - index.pdf

website:
  title: "István Magyary"
  favicon: images/favicon.ico
  announcement:
    icon: cash-coin
    dismissable: false
    content: "**Hi there!** - if you like my content you can buy me a coffee at [coff.ee/magyary](https://coff.ee/magyary){.btn .btn-primary .btn-sm .align-middle}."
    type: primary
    position: below-navbar
  navbar:
    left:
      - href: index.html
        text: "Blog" 
      - href: about.qmd
        text: "About me"
  twitter-card: true
  open-graph: true
  google-analytics:
    tracking-id: "G-3BVSFTG6L3"
    anonymize-ip: true
  cookie-consent: 
    palette: dark
  page-footer: 
    left: "Created by István Magyary using Quarto"
    right: "© 2025" 

format:
  html:
    theme: 
      light: quartz
      dark: darkly
    css: styles.css
    toc: true
    include-in-header: utils/auth-widget.html

pdf:
  toc: false
  number-sections: false
  colorlinks: true



