project:
  type: website
  resources:
    - index.pdf

website:
  title: "István Magyary"
  favicon: images/favicon.ico
  navbar:
    left:
      - href: index.html
        text: "Blog" 
      - href: about.qmd
        text: "About me"
  twitter-card: true
  open-graph: true
  google-analytics:
    tracking-id: "G-3BVSFTG6L3"
    anonymize-ip: true
  cookie-consent: 
    palette: dark
  page-footer: 
    left: "Created by István Magyary"
    right: "© 2025"
  announcement: 
    icon: cash-coin
    dismissable: true
    content: "**Hi!** - if you like my content you can buy me a coffe at [coff.ee/magyary](https://coff.ee/magyary)."
    type: primary
    position: below-navbar

format:
  html:
    theme: 
      light: quartz
      dark: darkly
    css: styles.css
    toc: true
    include-after-body: utils/medium-widget.html

pdf:
  toc: false
  number-sections: false
  colorlinks: true



